/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_euler;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author x
 */
public class Problem_01_02 {

    public static void main(String[] args) {
        
        System.out.println(problem_2(1,2,0));
    }

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    public static int problem_2(int previous, int current, int sum) {
        int next = previous + current;
        if (next < 4000000) {
            if (next % 2 == 0) {
                sum += next;
            }
            return problem_2(current, next, sum);
        } else {
            return sum+2;
        }
    }

    //sum of all values divisible by 3 or 5 from 1 to 1000
    public void problem_1() {
        int sum = 0;
        for (int i = 1; i < 1000; i++) {
            if (i % 3 == 0 || i % 5 == 0) {
                sum += i;
            }
        }
        System.out.println(sum);
    }
}
